name: Deploy Data Source

on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Profile'
        type: string
        required: true

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Add .env
      run: |
        touch .env
        echo "TARGET_SNOWFLAKE_PASSWORD='${{ secrets.SNOWFLAKE_PWD }}'" >> .env
        echo "DBT_SNOWFLAKE_PASSWORD='${{ secrets.SNOWFLAKE_PWD }}'" >> .env
        echo "GOODDATA_API_TOKEN='${{ secrets.GD_DEV_TOKEN }}'" >> .env
        echo "GOODDATA_API_TOKEN_DEMO='${{ secrets.GD_DEMO_TOKEN }}'" >> .env
    - name: Execute the data source deployment
      run: |
        python scripts/deploy.py --profile ${{ inputs.profile }}
